/// Generated by AssetsRefGenerator on 2020/08/17
class Res {
  static const String arrow_left = "assets/icons/arrow-left.svg";
  static const String menu = "assets/icons/menu.svg";
  static const String more_vertical = "assets/icons/more-vertical.svg";
  static const String person = "assets/icons/person.svg";
  static const String search = "assets/icons/search.svg";
  static const String shopping_bag = "assets/icons/shopping-bag.svg";
  static const String star = "assets/icons/star.svg";
  static const String business = "assets/images/business.png";
  static const String marketing = "assets/images/marketing.png";
  static const String music = "assets/images/music.png";
  static const String photography = "assets/images/photography.png";
  static const String user = "assets/images/user.jpg";
  static const String ux_big = "assets/images/ux_big.png";
  static const String ux_design = "assets/images/ux_design.png";
}
